In [43]:
# data encoding>> converting categorical colums into numeric

In [44]:
# 1 nominal/OHE
# 2 label and ordinal encoding
# 3 target guided ordinal encoding

In [45]:
# 1 Nominal / One hot encoding(OHE):>> it generate binary vector for each category

# eg: single, married, separated
# single: [1,0,0]
# married: [0,1,0]
# separated[0,0,1] 

In [46]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [47]:
df=pd.DataFrame({'status':['single', 'married', 'seperated', 'single', 'married', 'single', 'seperated', 'single', 'married']})

In [48]:
df

status
0     single
1    married
2  seperated
3     single
4    married
5     single
6  seperated
7     single
8    married

In [49]:
encoder=OneHotEncoder()

In [50]:
encoder

OneHotEncoder()

In [51]:
encoder.fit_transform(df[['status']])

<9x3 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [52]:
encoded=encoder.fit_transform(df[['status']]).toarray()

In [53]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [54]:
encoder.get_feature_names_out()

array(['status_married', 'status_seperated', 'status_single'],
      dtype=object)

In [55]:
encoder_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [56]:
encoder_df

status_married  status_seperated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             1.0               0.0            0.0
5             0.0               0.0            1.0
6             0.0               1.0            0.0
7             0.0               0.0            1.0
8             1.0               0.0            0.0

In [57]:
# new data
encoder.transform([['single']]).toarray()

C:\Users\91830\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [58]:
df

status
0     single
1    married
2  seperated
3     single
4    married
5     single
6  seperated
7     single
8    married

In [59]:
pd.concat([df,encoder_df], axis=1)

status  status_married  status_seperated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  seperated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0
5     single             0.0               0.0            1.0
6  seperated             0.0               1.0            0.0
7     single             0.0               0.0            1.0
8    married             1.0               0.0            0.0

In [60]:
# we can remove one dummy varable
# if there are n dummy variable then n-1 will make sence

In [61]:
df

status
0     single
1    married
2  seperated
3     single
4    married
5     single
6  seperated
7     single
8    married

In [62]:
# we can also do this by pandas

In [63]:
df_encoded=pd.get_dummies(df)

In [64]:
df_encoded

status_married  status_seperated  status_single
0           False             False           True
1            True             False          False
2           False              True          False
3           False             False           True
4            True             False          False
5           False             False           True
6           False              True          False
7           False             False           True
8            True             False          False

In [65]:
# Ensure that the columns are converted to integers
df_encoded = df_encoded.astype(int)


In [66]:
df_encoded

status_married  status_seperated  status_single
0               0                 0              1
1               1                 0              0
2               0                 1              0
3               0                 0              1
4               1                 0              0
5               0                 0              1
6               0                 1              0
7               0                 0              1
8               1                 0              0

In [67]:
# internal assignment try this on tips dataset

In [68]:
import seaborn as sns

In [69]:
df_tips=sns.load_dataset('tips')

In [70]:
df_tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [71]:
from sklearn.preprocessing import OneHotEncoder

In [72]:
encoder=OneHotEncoder()

In [73]:
encoded_tips=encoder.fit_transform(df_tips[['sex', 'smoker', 'day', 'time']]).toarray()

In [74]:
encoded_tips

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [75]:
encoder.get_feature_names_out()

array(['sex_Female', 'sex_Male', 'smoker_No', 'smoker_Yes', 'day_Fri',
       'day_Sat', 'day_Sun', 'day_Thur', 'time_Dinner', 'time_Lunch'],
      dtype=object)

In [76]:
encoded_df=pd.DataFrame(encoded_tips, columns=encoder.get_feature_names_out())

In [77]:
encoded_df

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
..          ...       ...        ...         ...      ...      ...      ...   
239         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
240         1.0       0.0        0.0         1.0      0.0      1.0      0.0   
241         0.0       1.0        0.0         1.0      0.0      1.0      0.0   
242         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
243         1.0       0.0        1.0         0.0      0.0      0.0      0.0   

     day_Thur  time_Dinner  time_Lunch  
0         0.0          1.0         0.0  
1         0.0          1.0         0.0  
2         0.0          1.0         0.0  
3         0.0          1.0         0.0  
4         0.0          1.0         0.0  
..        ...          ...         ...  
239       0.0          1.0         0.0  
240       0.0          1.0         0.0  
241       0.0          1.0         0.0  
242       0.0          1.0         0.0  
243       1.0          1.0         0.0  

[244 rows x 10 columns]

Label encoding

In [78]:
# 2 label and ordinal encoding
    # (i) label encoding>> assign unique label to the cagtegory

In [79]:
from sklearn.preprocessing import LabelEncoder

In [80]:
df

status
0     single
1    married
2  seperated
3     single
4    married
5     single
6  seperated
7     single
8    married

In [81]:
label_encoder=LabelEncoder()

In [82]:
label_encoder

LabelEncoder()

In [83]:
label_encoder.fit_transform(df[['status']])

C:\Users\91830\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0, 2, 1, 2, 0])

In [84]:
# for new data: 
label_encoder.transform([['single']])

C:\Users\91830\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [85]:
label_encoder.transform([['seperated']])

C:\Users\91830\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

Ordinal encoding

In [86]:
# (ii) ordinal encoding: 

# high school: 1
# graduate: 2
# post gra. 3
# phd: 4

# there are hierarchy

In [87]:
from sklearn.preprocessing import OrdinalEncoder

In [88]:
df=pd.DataFrame({'qualification': ['HS', 'GR', 'PG', 'PHD','HS', 'GR','PG','PHD','PG', 'PG', 'PHD']})

In [89]:
df

qualification
0             HS
1             GR
2             PG
3            PHD
4             HS
5             GR
6             PG
7            PHD
8             PG
9             PG
10           PHD

In [90]:
ordinal_encoder=OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PHD']])
                                        #   [0,    1,    2,    3   ]

In [91]:
ordinal_encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [1.],
       [2.],
       [3.],
       [2.],
       [2.],
       [3.]])

In [92]:
#for new
ordinal_encoder.transform([['PHD']]) 

C:\Users\91830\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[3.]])

target guided ordinal encoding

In [93]:
# 3 target guided ordinal encoding


# relationship with target variable
# a lot of uniqe categoris
# replace the cagtegory with the mean and median of respective group target

In [94]:
df=pd.DataFrame({'time':['lunch','breakfast', 'dinner','lunch','lunch','breakfast', 'dinner','lunch', 'lunch','breakfast', 'dinner'],
              'total_bill': [120,130,90,125,150,190,160,180,189,124,165]})

In [95]:
df

time  total_bill
0       lunch         120
1   breakfast         130
2      dinner          90
3       lunch         125
4       lunch         150
5   breakfast         190
6      dinner         160
7       lunch         180
8       lunch         189
9   breakfast         124
10     dinner         165

In [96]:
df.groupby('time')

In [97]:
df.groupby('time')['total_bill']

In [98]:
df.groupby('time')['total_bill'].mean()

time
breakfast    148.000000
dinner       138.333333
lunch        152.800000
Name: total_bill, dtype: float64

In [99]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [100]:
mean_price

{'breakfast': 148.0, 'dinner': 138.33333333333334, 'lunch': 152.8}

In [101]:
df['time_encoded']=df['time'].map(mean_price)

In [102]:
df

time  total_bill  time_encoded
0       lunch         120    152.800000
1   breakfast         130    148.000000
2      dinner          90    138.333333
3       lunch         125    152.800000
4       lunch         150    152.800000
5   breakfast         190    148.000000
6      dinner         160    138.333333
7       lunch         180    152.800000
8       lunch         189    152.800000
9   breakfast         124    148.000000
10     dinner         165    138.333333

In [103]:
#internal assignment: 
        #try this on tips dataset

In [104]:
import seaborn as sns

In [105]:
df=sns.load_dataset('tips')

In [106]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [107]:
mean_value=df.groupby('day')['total_bill'].mean().to_dict()

C:\Users\91830\AppData\Local\Temp\ipykernel_19088\1373860778.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_value=df.groupby('day')['total_bill'].mean().to_dict()


In [108]:
mean_value

{'Thur': 17.682741935483868,
 'Fri': 17.15157894736842,
 'Sat': 20.44137931034483,
 'Sun': 21.41}

In [109]:
df['day_encoded']=df['day'].map(mean_value)

In [110]:
df

total_bill   tip     sex smoker   day    time  size day_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2   21.410000
1         10.34  1.66    Male     No   Sun  Dinner     3   21.410000
2         21.01  3.50    Male     No   Sun  Dinner     3   21.410000
3         23.68  3.31    Male     No   Sun  Dinner     2   21.410000
4         24.59  3.61  Female     No   Sun  Dinner     4   21.410000
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3   20.441379
240       27.18  2.00  Female    Yes   Sat  Dinner     2   20.441379
241       22.67  2.00    Male    Yes   Sat  Dinner     2   20.441379
242       17.82  1.75    Male     No   Sat  Dinner     2   20.441379
243       18.78  3.00  Female     No  Thur  Dinner     2   17.682742

[244 rows x 8 columns]

In [111]:
#thanks