In [104]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [105]:
from sklearn.datasets import load_iris

In [106]:
data=load_iris()

In [107]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [108]:
df=pd.DataFrame(data.data, columns=data.feature_names)

In [109]:
df['target']=data.target

In [110]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [111]:
df=df.drop('petal width (cm)', axis=1)

In [112]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  target
0                  5.1               3.5                1.4       0
1                  4.9               3.0                1.4       0
2                  4.7               3.2                1.3       0
3                  4.6               3.1                1.5       0
4                  5.0               3.6                1.4       0
..                 ...               ...                ...     ...
145                6.7               3.0                5.2       2
146                6.3               2.5                5.0       2
147                6.5               3.0                5.2       2
148                6.2               3.4                5.4       2
149                5.9               3.0                5.1       2

[150 rows x 4 columns]

In [113]:
df['target'].unique()

array([0, 1, 2])

In [114]:
import plotly.express as px
fig=px.scatter_3d(data_frame=df, x='sepal length (cm)', y='sepal width (cm)', z='petal length (cm)', color=df['target'], width=1000, height=800)
fig.show()

In [115]:
# step 1: 

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [116]:
df.iloc[:, 0:3]=scaler.fit_transform(df.iloc[:, 0:3])

In [117]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  target
0            -0.900681          1.019004          -1.340227       0
1            -1.143017         -0.131979          -1.340227       0
2            -1.385353          0.328414          -1.397064       0
3            -1.506521          0.098217          -1.283389       0
4            -1.021849          1.249201          -1.340227       0
..                 ...               ...                ...     ...
145           1.038005         -0.131979           0.819596       2
146           0.553333         -1.282963           0.705921       2
147           0.795669         -0.131979           0.819596       2
148           0.432165          0.788808           0.933271       2
149           0.068662         -0.131979           0.762758       2

[150 rows x 4 columns]

In [118]:
# step 2 covariance matrix: 
covariance_matrix=np.cov([df.iloc[:,0], df.iloc[:, 1], df.iloc[:,2]])

In [119]:
covariance_matrix

array([[ 1.00671141, -0.11835884,  0.87760447],
       [-0.11835884,  1.00671141, -0.43131554],
       [ 0.87760447, -0.43131554,  1.00671141]])

In [120]:
# step 3 eigen decomposiotn of covaricne matrix: 

eigen_values, eigen_vectors=np.linalg.eig(covariance_matrix)


# numpy.linalg.eig
# linalg.eig(a)[source]
# Compute the eigenvalues and right eigenvectors of a square array.

In [121]:
eigen_values   # lemda1, lemda3, lemda2

array([2.0349965 , 0.07161299, 0.91352474])

In [122]:
eigen_vectors

array([[-0.62906623,  0.64532277,  0.43339843],
       [ 0.36114435, -0.25109527,  0.89806788],
       [-0.68836795, -0.72146357,  0.07509912]])

In [142]:
pc=eigen_vectors[[0,2]]   # because we want 3D to 2D

In [143]:
pc  

array([[-0.62906623,  0.64532277,  0.43339843],
       [-0.68836795, -0.72146357,  0.07509912]])

In [144]:
df.shape

(150, 4)

In [145]:
tranformed_df=np.dot(df.iloc[:, 0:3], pc.T)

In [147]:
tranformed_df.shape

(150, 2)

In [148]:
new_df=pd.DataFrame(tranformed_df, columns=['PC1', 'PC2'])
new_df['target']=df['target'].values

In [149]:
new_df

PC1       PC2  target
0    0.643323 -0.215824       0
1    0.053012  0.781385       0
2    0.477926  0.611775       0
3    0.454864  0.869799       0
4    0.868097 -0.298495       0
..        ...       ...     ...
145 -0.382932 -0.557760       2
146 -0.870064  0.597728       2
147 -0.230486 -0.390944       2
148  0.641653 -0.796497       2
149  0.202216  0.105236       2

[150 rows x 3 columns]

In [150]:
new_df.shape

(150, 3)

In [152]:
px.scatter(x=new_df['PC1'], y=new_df['PC2'], color=new_df['target'])