In [2]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000, n_features=10,n_informative=5, n_redundant=5,n_classes=3, random_state=1)

In [3]:
y

array([1, 0, 1, 2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 1, 0, 2, 0,
       2, 2, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 2, 1,
       1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 1, 2, 2, 2,
       0, 1, 0, 2, 1, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 2, 2,
       1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 0, 1,
       0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 2, 0, 1, 2, 0, 2, 1, 2, 0, 0, 1,
       0, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       2, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0, 2,
       0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 0, 2, 2,
       1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2,
       1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1,
       1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 0, 0, 2, 1, 1,

In [4]:
X

array([[ 1.89149379, -0.39847585,  1.63856893, ...,  0.58810926,
        -0.02542177, -0.52835426],
       [ 1.86913773, -0.56336215,  2.03411807, ..., -0.55633   ,
        -0.27340013,  0.72129251],
       [ 1.95259701, -2.83144572,  0.19055535, ..., -0.60957741,
        -2.07750191, -1.75469982],
       ...,
       [ 1.98033054,  1.37228804,  1.67376262, ...,  2.75687956,
        -0.20719842,  0.39299534],
       [-1.54305631, -0.27530218,  0.38744703, ...,  0.72769107,
         0.51983329, -1.92306657],
       [ 1.17970389, -3.3812155 , -0.1498426 , ...,  1.24640268,
        -4.00356845, -3.01027048]])

In [7]:
# multiclassification problem: 

# 1 one vs test
# 2 multinomial method softmax regression

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.30, random_state=1)

In [10]:
X_train.shape, X_test.shape

((700, 10), (300, 10))

In [8]:
from sklearn.linear_model import LogisticRegression

In [11]:
#mult_class>>  ovr, multinomial, auto by default this will be auto
# solver{‘lbfgs’, ‘liblinear’, ‘newton-cg’, ‘newton-cholesky’, ‘sag’, ‘saga’}, default=’lbfgs’>Algorithm to use in the optimization problem.
# solver is help to find the optimal coffcients(thetas)
model=LogisticRegression(multi_class='ovr',solver='lbfgs')

In [13]:
model

LogisticRegression(multi_class='ovr')

In [12]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [14]:
y_pred=model.predict(X_test)

In [15]:
y_pred

array([1, 2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0,
       2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 2, 2, 0, 1,
       0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 2, 2, 2, 1, 2, 0,
       0, 2, 0, 0, 0, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 2, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 2, 0, 2, 2, 1, 1, 1,
       1, 1, 2, 0, 0, 1, 2, 1, 2, 0, 0, 2, 2, 0, 2, 0, 1, 0, 2, 1, 1, 2,
       1, 1, 1, 2, 0, 2, 1, 0, 1, 0, 1, 1, 0, 2, 2, 2, 1, 2, 0, 2, 0, 2,
       1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0,
       0, 2, 2, 1, 2, 0, 0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 2, 1,
       0, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1, 0, 0, 0, 1, 2,
       1, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 1, 2,
       0, 1, 0, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 0, 2,
       0, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 2,
       1, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 2, 2, 1])

In [16]:
y_pred_proba=model.predict_proba(X_test)

In [17]:
y_pred_proba

array([[3.01147443e-01, 6.09509153e-01, 8.93434033e-02],
       [3.39370126e-01, 1.16944327e-01, 5.43685546e-01],
       [4.73057984e-01, 2.41161193e-01, 2.85780823e-01],
       [3.95802916e-01, 1.23530190e-01, 4.80666894e-01],
       [4.47776155e-02, 3.54108723e-01, 6.01113662e-01],
       [8.59031818e-01, 9.25919400e-02, 4.83762423e-02],
       [1.38033483e-01, 7.46757334e-01, 1.15209183e-01],
       [2.51161783e-01, 4.60307931e-01, 2.88530286e-01],
       [7.20799683e-02, 8.59945770e-02, 8.41925455e-01],
       [2.83491820e-02, 1.61251687e-01, 8.10399131e-01],
       [5.02136692e-01, 3.78696744e-01, 1.19166563e-01],
       [6.45478477e-01, 6.07492610e-02, 2.93772262e-01],
       [4.86332965e-01, 1.26376052e-01, 3.87290983e-01],
       [2.39696655e-02, 2.35903975e-01, 7.40126360e-01],
       [5.03520043e-01, 1.46781947e-01, 3.49698010e-01],
       [6.20609394e-01, 1.90194368e-02, 3.60371169e-01],
       [4.99389228e-01, 4.92328134e-01, 8.28263779e-03],
       [2.92334832e-03, 6.28931

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[75 21  3]
 [10 58 21]
 [23 14 75]]
0.6933333333333334
              precision    recall  f1-score   support

           0       0.69      0.76      0.72        99
           1       0.62      0.65      0.64        89
           2       0.76      0.67      0.71       112

    accuracy                           0.69       300
   macro avg       0.69      0.69      0.69       300
weighted avg       0.70      0.69      0.69       300



In [19]:
# 2 multinomial

In [20]:
model=LogisticRegression(multi_class='multinomial',solver='lbfgs')

In [21]:
model

LogisticRegression(multi_class='multinomial')

In [22]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

In [23]:
y_pred=model.predict(X_test)

In [24]:
y_pred


array([1, 2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0,
       2, 1, 2, 2, 2, 0, 2, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 2, 2, 2, 1,
       0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 2, 2, 2, 1, 2, 0,
       0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 0, 2, 2, 1, 0, 1, 2, 2, 2, 1,
       1, 1, 2, 0, 2, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 2, 0, 2, 2, 1, 1, 1,
       1, 1, 2, 0, 0, 1, 2, 1, 2, 0, 0, 2, 2, 0, 2, 0, 1, 0, 2, 0, 1, 2,
       2, 1, 1, 1, 0, 2, 1, 0, 1, 0, 1, 1, 0, 2, 2, 2, 1, 2, 0, 2, 0, 2,
       1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 0,
       0, 2, 2, 1, 2, 0, 0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 2, 1,
       0, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 0, 0, 0, 1, 2,
       1, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 1, 2,
       0, 1, 0, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 0, 2,
       0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 2,
       1, 1, 0, 1, 0, 0, 0, 2, 0, 1, 0, 2, 2, 1])

In [25]:
y_pred_proba=model.predict_proba(X_test)

In [26]:
y_pred_proba

array([[3.15962118e-01, 5.72771928e-01, 1.11265954e-01],
       [3.00597343e-01, 1.25972242e-01, 5.73430415e-01],
       [4.70313362e-01, 2.28329069e-01, 3.01357569e-01],
       [3.55249326e-01, 1.39303753e-01, 5.05446922e-01],
       [4.87226066e-02, 3.48473729e-01, 6.02803664e-01],
       [9.48898931e-01, 2.83876733e-02, 2.27133956e-02],
       [1.28907970e-01, 7.64660539e-01, 1.06431490e-01],
       [2.40430174e-01, 4.74838342e-01, 2.84731484e-01],
       [5.30590290e-02, 6.07249046e-02, 8.86216066e-01],
       [1.60410839e-02, 1.04958493e-01, 8.79000423e-01],
       [5.17839578e-01, 3.47549892e-01, 1.34610530e-01],
       [6.77135319e-01, 6.25300634e-02, 2.60334618e-01],
       [4.64192706e-01, 1.41017736e-01, 3.94789558e-01],
       [2.61536673e-02, 1.63500772e-01, 8.10345561e-01],
       [4.90307607e-01, 1.57912102e-01, 3.51780290e-01],
       [6.68251341e-01, 2.18281835e-02, 3.09920475e-01],
       [5.70813496e-01, 4.16834900e-01, 1.23516045e-02],
       [4.13661151e-03, 7.92833

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[70 21  8]
 [13 57 19]
 [21 13 78]]
0.6833333333333333
              precision    recall  f1-score   support

           0       0.67      0.71      0.69        99
           1       0.63      0.64      0.63        89
           2       0.74      0.70      0.72       112

    accuracy                           0.68       300
   macro avg       0.68      0.68      0.68       300
weighted avg       0.69      0.68      0.68       300

