In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
 
import warnings
warnings.filterwarnings('ignore')

In [38]:
df=pd.read_csv('winequalityN.csv')

In [39]:
df

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [40]:
df.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [42]:
df.type.unique()

array(['white', 'red'], dtype=object)

In [43]:
df['type']=df['type'].map({'white': 1, 'red': 0})

In [44]:
df['type'].unique()

array([1, 0], dtype=int64)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   int64  
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 660.0 KB


In [46]:
df.isna().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [47]:
df=df.dropna()

In [48]:
df.isna().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [49]:
df.shape

(6463, 13)

In [50]:
df.duplicated().sum()

1168

In [51]:
df=df.drop_duplicates()

In [52]:
df.shape

(5295, 13)

In [65]:
X=df.drop('quality', axis=1)
y=df['quality']

In [66]:
X

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0        1            7.0             0.270         0.36            20.7   
1        1            6.3             0.300         0.34             1.6   
2        1            8.1             0.280         0.40             6.9   
3        1            7.2             0.230         0.32             8.5   
6        1            6.2             0.320         0.16             7.0   
...    ...            ...               ...          ...             ...   
6490     0            6.3             0.510         0.13             2.3   
6491     0            6.8             0.620         0.08             1.9   
6492     0            6.2             0.600         0.08             2.0   
6495     0            5.9             0.645         0.12             2.0   
6496     0            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
6         0.045                 30.0                 136.0  0.99490  3.18   
...         ...                  ...                   ...      ...   ...   
6490      0.076                 29.0                  40.0  0.99574  3.42   
6491      0.068                 28.0                  38.0  0.99651  3.42   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  
0          0.45      8.8  
1          0.49      9.5  
2          0.44     10.1  
3          0.40      9.9  
6          0.47      9.6  
...         ...      ...  
6490       0.75     11.0  
6491       0.82      9.5  
6492       0.58     10.5  
6495       0.71     10.2  
6496       0.66     11.0  

[5295 rows x 12 columns]

In [67]:
y

0       6
1       6
2       6
3       6
6       6
       ..
6490    6
6491    6
6492    5
6495    5
6496    6
Name: quality, Length: 5295, dtype: int64

In [77]:
y.unique()

array([6, 5, 7, 8, 4, 3, 9], dtype=int64)

In [68]:
X.dtypes

type                      int64
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
dtype: object

In [69]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(X,y, test_size=0.30, random_state=1)

In [70]:
X_train.shape, X_test.shape

((3706, 12), (1589, 12))

In [71]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()

In [72]:
clf

LogisticRegression()

In [73]:
clf.fit(X_train, y_train)

LogisticRegression()

In [74]:
y_pred=clf.predict(X_test)

In [75]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           3       0.00      0.00      0.00        11
           4       0.00      0.00      0.00        60
           5       0.50      0.46      0.48       522
           6       0.46      0.72      0.56       689
           7       0.31      0.02      0.03       261
           8       0.00      0.00      0.00        45
           9       0.00      0.00      0.00         1

    accuracy                           0.47      1589
   macro avg       0.18      0.17      0.15      1589
weighted avg       0.41      0.47      0.40      1589

[[  0   0   2   8   0   1   0]
 [  0   0  22  38   0   0   0]
 [  0   0 240 279   3   0   0]
 [  0   0 186 498   5   0   0]
 [  0   0  30 227   4   0   0]
 [  0   0   2  42   1   0   0]
 [  0   0   0   1   0   0   0]]


In [ ]:
# hw try the accuracy by hyper parameter tuning, cross validation
